### ISSUE TITLE
space_travelers_hub kanban board creation

### ISSUE THREAD

**Issue by jorgeabrahan** [jorgeabrahan/space_travelers_hub#25]
Project link: [https://github.com/jorgeabrahan/space_travelers_hub/projects/1](https://github.com/jorgeabrahan/space_travelers_hub/projects/1)

Team members:
1- Jorge Abrahan
2- Nelson Araujo

**Comment by zainsadaqat** [comment]
# Pull Request Approved ✅ 🎊 🎉 
## Hello TEAM! 👋 

## Things to Appreciate 
- [ ] Correct Flow ✅ 
- [ ] Clean Code 👍 
- [ ] No Linter Errors 🔥 
- [ ] Descriptive Pull Request and Summary 👌 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media4.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
